export const CIVILIZATIONS = [
  "abbasid_dynasty",
  "ayyubids",
  "byzantines",
  "chinese",
  "delhi_sultanate",
  "english",
  "french",
  "golden_horde",
  "house_of_lancaster",
  "holy_roman_empire",
  "japanese",
  "jeanne_darc",
  "jin_dynasty",
  "knights_templar",
  "macedonian_dynasty",
  "malians",
  "mongols",
  "order_of_the_dragon",
  "ottomans",
  "rus",
  "sengoku_daimyo",
  "tughlaq_dynasty",
  "zhu_xis_legacy",
] as const;

export type Civilization = (typeof CIVILIZATIONS)[number];

export const CIVILIZATION_FLAGS: Record<Civilization, string> = {
  abbasid_dynasty: "/civilizations/abbasid_dynasty.webp",
  ayyubids: "/civilizations/ayyubids.webp",
  byzantines: "/civilizations/byzantines.webp",
  chinese: "/civilizations/chinese.webp",
  delhi_sultanate: "/civilizations/delhi_sultanate.webp",
  english: "/civilizations/english.webp",
  french: "/civilizations/french.webp",
  golden_horde: "/civilizations/golden_horde.webp",
  house_of_lancaster: "/civilizations/house_of_lancaster.webp",
  holy_roman_empire: "/civilizations/holy_roman_empire.webp",
  japanese: "/civilizations/japanese.webp",
  jeanne_darc: "/civilizations/jeanne_darc.webp",
  jin_dynasty: "/civilizations/jin_dynasty.webp",
  knights_templar: "/civilizations/knights_templar.webp",
  macedonian_dynasty: "/civilizations/macedonian_dynasty.webp",
  malians: "/civilizations/malians.webp",
  mongols: "/civilizations/mongols.webp",
  order_of_the_dragon: "/civilizations/order_of_the_dragon.webp",
  ottomans: "/civilizations/ottomans.webp",
  rus: "/civilizations/rus.webp",
  sengoku_daimyo: "/civilizations/sengoku_daimyo.webp",
  tughlaq_dynasty: "/civilizations/tughlaq_dynasty.webp",
  zhu_xis_legacy: "/civilizations/zhu_xis_legacy.webp",
};

export const CURRENT_RM_SOLO_MAPS = [
  "Dry Arabia",
  "Hill and Dale",
  "Rocky River",
  "Sunkenlands",
  "Wasteland",
  "King of the Hill",
  "Relic River",
  "Waterholes",
  "Archipelago",
  "Cliffside",
  "Craters",
  "Himeyama",
  "Highwoods",
  "West Lake",
  "Danube River",
  "Migration",
] as const;
