export const CIVILIZATIONS = [
  "abbasid_dynasty",
  "ayyubids",
  "byzantines",
  "chinese",
  "delhi_sultanate",
  "english",
  "french",
  "golden_horde",
  "house_of_lancaster",
  "holy_roman_empire",
  "japanese",
  "jeanne_darc",
  "jin_dynasty",
  "knights_templar",
  "macedonian_dynasty",
  "malians",
  "mongols",
  "order_of_the_dragon",
  "ottomans",
  "rus",
  "sengoku_daimyo",
  "tughlaq_dynasty",
  "zhu_xis_legacy",
] as const;

export type Civilization = (typeof CIVILIZATIONS)[number];

export const CIVILIZATION_FLAGS: Record<Civilization, string> = {
  abbasid_dynasty: "/civilizations/Abbasid_Dynasty_AoE4.png",
  ayyubids: "/civilizations/Ayyubid%20flag.png",
  byzantines: "/civilizations/Byzantines_AoE4.png",
  chinese: "/civilizations/China%20Flag.png",
  delhi_sultanate: "/civilizations/Delhi_Sultanate_AoE4.png",
  english: "/civilizations/English_AoE4.png",
  french: "/civilizations/French_AoE4.png",
  golden_horde: "/civilizations/golden%20horde%20flag.png",
  house_of_lancaster: "/civilizations/House_of_Lancaster_AoE4.png",
  holy_roman_empire: "/civilizations/HRE_AoE4.png",
  japanese: "/civilizations/Japanese_AoE4.png",
  jeanne_darc: "/civilizations/Jeanne_d_Arc_AoE4.png",
  jin_dynasty: "/civilizations/Jin_Dynasty_AoE4.png",
  knights_templar: "/civilizations/Knights_Templar_AoE4.png",
  macedonian_dynasty: "/civilizations/macedonian%20dynasty%20flag.png",
  malians: "/civilizations/Malians_AoE4.png",
  mongols: "/civilizations/Mongols_AoE4.png",
  order_of_the_dragon: "/civilizations/Order_of_the_Dragon_AoE4.png",
  ottomans: "/civilizations/Ottomans_AoE4.png",
  rus: "/civilizations/Rus_AoE4.png",
  sengoku_daimyo: "/civilizations/sengoku%20flag.png",
  tughlaq_dynasty: "/civilizations/tughlaq%20flag.png",
  zhu_xis_legacy: "/civilizations/Zhu_Xis_Legacy_AoE4.png",
};

export const CURRENT_RM_SOLO_MAPS = [
  "Dry Arabia",
  "Hill and Dale",
  "Rocky River",
  "Sunkenlands",
  "Wasteland",
  "King of the Hill",
  "Relic River",
  "Waterholes",
  "Archipelago",
] as const;
